config/routes.rb
Mccs::Application.routes.draw do

  root to: "welcome#home"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
      controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :players do 
    resources :comments, only: [:create]
  end
  resources :matches
    get 'matches/:id/team_a_inning' => 'matches#team_a_inning', :as => :add_team_a_inning
    get 'matches/:id/team_b_inning' => 'matches#team_b_inning', :as => :add_team_b_inning
  resources :innings, only: [:new, :create]
  resources :venues
  resources :umpires
  resources :series
  resources :teams
  resources :team_flags, only: [:show]
  resources :clubs
  resources :club_flags, only: [:show]  

  resources :users, only: [:edit, :update]
  resources :authorizations, only: [:index, :show]

  namespace :admin do
    get 'dashboard/home' => "dashboard#home", as: :dashboard_home
    resources :dashboard, only: [:home]
    resources :authorizations, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  
end

app/models/player.rb
class Player < ActiveRecord::Base
  belongs_to :team
  belongs_to :player_type
  belongs_to :bowling_style
  has_many :batsman_in_innings
  has_many :bowler_in_innings
  has_many :comments
  has_many :batsman_in_innings, :class_name => "BatsmanInInning", :foreign_key => "out_fielder_id"
  has_many :batsman_in_innings, :class_name => "BatsmanInInning", :foreign_key => "out_bowler_id"

  belongs_to :team
  belongs_to :user
  belongs_to :player_type
  belongs_to :player_bowling_style
  has_many :batsman_in_innings
  has_many :bowler_in_innings

  has_many :batsman_in_innings, :class_name => "BatsmanInInning", :foreign_key => "out_fielder_id"
  has_many :batsman_in_innings, :class_name => "BatsmanInInning", :foreign_key => "out_bowler_id" 
  
  validates_presence_of :name, :player_type,:player_batting_style, :player_bowling_style, :date_of_birth, on: :create
  
  has_attached_file :picture_url
  validates_attachment_content_type :picture_url, 
      :content_type => ["image/jpg", "image/jpeg", "image/png"]
  
  validates_attachment_size :picture_url, 
      :less_than => 2.megabytes, message: "File size must be less than 2 MB"
  
  def age(dob)
    now = Time.now.utc.to_date
    now.year - dob.year - ((now.month > dob.month || (now.month == dob.month && now.day >= dob.day)) ? 0 : 1)
  end

end

app/models/player_type.rb
class PlayerType < ActiveRecord::Base
  has_many :players
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_player, only: [:new_player, :show, :edit, :update, :destroy]

  # GET /players
  # GET /players.json
  def index
    if current_user.present?
      @players = Player.where(:user_id => current_user.id)
    else
      @players = Player.all
    end
  end

  def new_player
  end

  # GET /players/1
  # GET /players/1.json
  def show
    @comment = Comment.new
    @comment.player_id = @player.id
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players
  # POST /players.json
  def create
    @player = Player.new(player_params)
    @player.user_id = current_user.id
    respond_to do |format|
      if @player.save
        if params[:player][:show].present? 
          toast('success','Player was successfully created!')
          format.html { redirect_to @player }
          format.json { render action: 'show', status: :created, location: @player }
          format.js { render action: 'new_player', status: :created, location: @player }
        else    
          format.html { redirect_to @player, toast('success','Player was successfully created!') }
          format.json { render action: 'show', status: :created, location: @player }
        end
      else
        format.html { render action: 'new' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1
  # PATCH/PUT /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to @player, toast('success',"Player was successfully updated!") }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1
  # DELETE /players/1.json
  def destroy
    @player.destroy
    respond_to do |format|
      format.html { redirect_to team_path(@player.team_id), toast('success',"Player was successfully removed from #{@player.team.name}!") }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def player_params
      params.require(:player).permit(:name, :player_batting_style, :best_performance, :worst_performance, :picture_url, :team_id, :user_id, :player_type_id, :player_bowling_style_id, :date_of_birth, :odi_debut, :test_debut, :t20_debut)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
  #****************
  #  T20 Deatails
  #****************   
  def t20_best_batting player
    runs = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                          .select("MAX(batsman_in_innings.runs) as runs")
                          .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2").first.runs    
    if runs
      balls = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                             .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2
                                     and batsman_in_innings.runs = #{runs}").first.balls
      best_batting = "#{runs} runs of #{balls} balls"
    end
  end
  
  def t20_best_bowling player
    wickets = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                            .select("MAX(bowler_in_innings.wickets) as wickets")
                            .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2").first.wickets
    if wickets
      runs = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                           .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2
                                   and bowler_in_innings.wickets = #{wickets}").first.runs
      overs = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                            .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2
                                   and bowler_in_innings.wickets = #{wickets}").first.overs.to_f
      best_bowling = "#{wickets} wickets and #{runs} runs in #{overs} overs"
    end
  end

  def t20_matches player
    bt_ct = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                           .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2").count
    if (bt_ct == 0) 
      bl_ct = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                            .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2").count
    else
      bt_ct
    end
  end
  
  def t20_bt_innings player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2").count
  end
  

  def t20_bt_runs player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2")
                   .sum("batsman_in_innings.runs")  
  end
  
  def t20_bt_not_out player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2 
                           and batsman_in_innings.out_id = 7").count
  end
  
  def t20_bt_average player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 2")
                   .average("runs").to_f
  end    

  def t20_bl_innings player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2").count
  end
  
  def t20_bl_runs player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2")
                  .sum("bowler_in_innings.runs")  
  end
      
  def t20_bl_balls player
    ov = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2")
                  .sum("bowler_in_innings.overs").round  
    balls = ov * 6              
  end
  
  def t20_bl_wickets player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 2")
                  .sum("bowler_in_innings.wickets")  
  end

  #****************
  # ODI Deatails
  #**************** 

  def odi_best_batting player
    runs = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                          .select("MAX(batsman_in_innings.runs) as runs")
                          .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1").first.runs    
    if runs
      balls = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                           .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1
                                   and batsman_in_innings.runs = #{runs}").first.balls
      best_batting = "#{runs} runs of #{balls} balls"
    end  
  end
  
  def odi_best_bowling player
    wickets = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                            .select("MAX(bowler_in_innings.wickets) as wickets")
                            .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1").first.wickets
    if wickets
      runs = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                         .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1
                                 and bowler_in_innings.wickets = #{wickets}").first.runs
      overs = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                          .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1
                                 and bowler_in_innings.wickets = #{wickets}").first.overs.to_f
      best_bowling = "#{wickets} wickets and #{runs} runs in #{overs} overs"
    end  
  end

  def odi_matches player
    bt_ct = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                           .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1").count
    if (bt_ct == 0) 
      bl_ct = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                            .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1").count
    else
      bt_ct
    end
  end
  
  def odi_bt_innings player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1").count
  end
  

  def odi_bt_runs player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1")
                   .sum("batsman_in_innings.runs")  
  end
  
  def odi_bt_not_out player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1 
                           and batsman_in_innings.out_id = 7").count
  end
  
  def odi_bt_average player
    BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                   .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id = 1")
                   .average("runs").to_f
  end    

  def odi_bl_innings player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1").count
  end
  
  def odi_bl_runs player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1")
                  .sum("bowler_in_innings.runs")  
  end
      
  def odi_bl_balls player
    ov = BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1")
                  .sum("bowler_in_innings.overs").round  
    balls = ov * 6              
  end
  
  def odi_bl_wickets player
    BowlerInInning.joins("Inner join matches on matches.id = bowler_in_innings.match_id")
                  .where("bowler_in_innings.player_id = #{player} and matches.competition_type_id = 1")
                  .sum("bowler_in_innings.wickets")  
  end 

  #****************
  # Test Deatails
  #**************** 

  def test_best_batting player
    runs = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                          .select("MAX(batsman_in_innings.runs) as runs")
                          .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id in ('3','4')").first.runs    
    if runs
      balls = BatsmanInInning.joins("Inner join matches on matches.id = batsman_in_innings.match_id")
                           .where("batsman_in_innings.player_id = #{player} and matches.competition_type_id in ('3','4')
                                   and batsman_in_innings.runs = #{runs}").first.balls
      best_batting = "#{runs} runs of #{balls} balls"
    end  
  end
  

app/views/players/_form.html.haml
= bootstrap_form_for(@player,inline_errors: false) do |f|
  - if @player.errors.any?
    :javascript
      var count = "Please resolve"+' '+  #{@player.errors.count}  +' '+ "error before submitting your request." ;
        Command: toastr.warning(count);    
  - @player.errors.full_messages.each do |msg|
    :javascript
      var msg = " #{msg} ";
      Command: toastr.error(msg);
  .row
    .col-sm-4
      = f.text_field :name
      = f.select :player_batting_style, [["Right-handed", "Right-handed"], ["Left-handed", "Left-handed"]], :prompt => "select"
      = f.collection_select :player_type_id, PlayerType.all, :id, :name, prompt: true
      = f.collection_select :player_bowling_style_id, PlayerBowlingStyle.all, :id, :name, prompt: true         

      = f.file_field :picture_url, label: "Add Player Image", accept: 'image/png,image/gif,image/jpeg'
      .input-group.margin
        %input#player_image.form-control{:type => "text", :disabled => true}
        %span.input-group-btn 
          %a.btn.btn-success.btn-flat{:onclick => "$('input[id=player_picture_url]').click();"} 
            Browse
      :javascript
        $('input[id=player_picture_url]').change(function() {
          $('#player_image').val($(this).val());
        });
    .col-sm-4
      = f.text_field :date_of_birth, :class => 'dob_datepicker', :placeholder => "mmmm dd, yyyy", append: "<i class='fa fa-calendar'></i>".html_safe
      = f.text_field :odi_debut, :placeholder => "mmmm dd, yyyy", :class => 'odi_datepicker', append: "<i class='fa fa-calendar'></i>".html_safe
      = f.text_field :test_debut, :placeholder => "mmmm dd, yyyy", :class => 'test_datepicker', append: "<i class='fa fa-calendar'></i>".html_safe
      = f.text_field :t20_debut, :placeholder => "mmmm dd, yyyy", :class => 't20_datepicker', append: "<i class='fa fa-calendar'></i>".html_safe
  .row
    .col-sm-8  
      = f.submit 'Update', :class => 'btn btn-primary pull-right' 

app/views/players/_sidenavbar.html.haml
/ sidebar: style can be found in sidebar.less
%section.sidebar
  / sidebar menu: : style can be found in sidebar.less
  %ul.sidebar-menu
    %li
      %a{href: root_path}
        %i.fa.fa-home
        %span Home
    %li
      %a{href: clubs_path}
        %i.fa.fa-star
        %span Clubs
    %li
      %a{href: teams_path}
        %i.fa.fa-flag
        %span Teams
    %li
      %a{href: series_index_path}
        %i.fa.fa-trophy
        %span Series
    %li
      %a{href: matches_path}
        %i.fa.fa-maxcdn
        %span Matches
    %li.active
      %a{href: players_path}
        %i.fa.fa-group
        %span Players
    %li
      %a{href: umpires_path}
        %i.ion.ion-android-contacts
        %span Umpires
    %li
      %a{href: venues_path}
        %i.fa.fa-umbrella
        %span Venues
    %li.social
      %span
        #{social_share_button_tag("MyClubCricketStats", :url => request.original_url, :image => "http://www.elphax.com/assets/images/my-club-cricket-stats.png", desc: "MyClubCricketStats is a club cricket statics management application where users can create/manage the Clubs, Teams, and Players. MyClubCricketStats will calculate and populates each player and team stats after entering and saving the data.")}        
/ /.sideba

app/views/players/index.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Manage Players
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home    
        %li.active
          %a{:href => players_path}
            %i.fa.fa-group
            Players
    / /.content-header
    %section.content
      .box.box-solid.box-primary
        .box-header
          %h3.box-title Players     
        .box-body  
          .table-responsive 
            %table.table.table-bordered.table-condensed{id: 'players'}
              %thead.player_head
                %tr
                  %th
                  %th Name
                  %th Age
                  %th Type
                  %th Batting style
                  %th Blowing style
                  %th Team
                  %th
              %tbody    
                - @players.each do |player|
                  %tr
                    %td.center
                      - if player.picture_url?
                        #{image_tag player.picture_url, :class => 'player_pic_small'}
                      - else
                        #{image_tag "player_default_pic.png", :class => 'player_pic_small'}                  
                    %td= link_to "#{player.name}", player, :title => "View player"  
                    %td= player.age(player.date_of_birth) if player.date_of_birth?
                    %td= player.player_type.name
                    %td= player.player_batting_style
                    %td= player.player_bowling_style.name
                    %td= player.team.name               
                    %td.center
                      - if current_user.present? && player.user_id == current_user.id
                        = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_player_path(player), :class => 'btn btn-xs btn-flat btn-default', :title => "Edit player" 
                        = link_to '<i class="fa fa-trash-o"></i>'.html_safe, player, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-xs btn-flat btn-danger', :title => "Remove player" 
      %br 

app/views/players/new_player.js.haml
$('#new_player_modal').modal_success();

app/views/players/show.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Manage Players
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home    
        %li.active
          %a{:href => players_path}
            %i.fa.fa-group
            Players
    / /.content-header
    %section.content
      .box.box-default
        #box.box
          .space
          .icon
            .image
              - if @player.picture_url.blank?
                %td= image_tag "player_default_pic.png", :class => "player_pic_small"
              - else
                %td= image_tag @player.picture_url, :class => "player_pic_small"
            .info
              %h3.title= @player.name
        
        .box-body
          .board
            .board-inner
              %ul#myTab.nav.nav-tabs
                .liner
                %li.active
                  %a{"data-toggle" => "tab", :href => "#bio", :title => "Player Information"}
                    %span.round-tabs.one
                      %i.fa.fa-user
                %li
                  %a{"data-toggle" => "tab", :href => "#t20", :title => "T20 Statistics"}
                    %span.round-tabs.two
                      T20
                      / <i class="glyphicon glyphicon-user"></i>
                %li
                  %a{"data-toggle" => "tab", :href => "#odi", :title => "ODI Statistics"}
                    %span.round-tabs.three
                      ODI
                      / <i class="glyphicon glyphicon-gift"></i>
                %li
                  %a{"data-toggle" => "tab", :href => "#test", :title => "Test Statistics"}
                    %span.round-tabs.four
                      Test
                      / <i class="glyphicon glyphicon-comment"> Test</i>
                %li
                  %a{"data-toggle" => "tab", :href => "#comment", :title => "Comments"}
                    %span.round-tabs.five
                      %i.fa.fa-comments
            .tab-content
              #bio.tab-pane.fade.in.active
                %section.narrow
                  %h3.bg-green Player Information
                  %table.table.table-bordered
                    %tbody
                      %tr
                        %td Title
                        %td= @player.player_type.name
                      %tr
                        %td Age
                        %td= @player.age(@player.date_of_birth) if @player.date_of_birth?
                      %tr
                        %td Played for
                        %td= @player.team.name
                      %tr
                        %td Batting Style
                        %td= @player.player_batting_style
                      %tr
                        %td Bowling Style
                        %td= @player.player_bowling_style.name
                      %tr
                        %td Played For
                        %td= @player.team.name
              #t20.tab-pane.fade
                %section.narrow
                  %h3.bg-yellow Player T20 Statistics
                  .text-center
                    %p 
                      Debut: 
                      - if @player.t20_debut?
                        %span.label.label-success 
                          #{@player.t20_debut.to_formatted_s(:long)}   
                    %p 
                      Matches Played: 
                      %span.label.label-success 
                        #{t20_matches(@player.id)}
                  .col-sm-6
                    %h5 Batting
                    %table.table.table-bordered
                      %tbody                
                        %tr
                          %td Innings
                          %td= t20_bt_innings(@player.id)
                        %tr
                          %td Runs
                          %td= t20_bt_runs(@player.id)
                        %tr
                          %td Not out
                          %td= t20_bt_not_out(@player.id)
                        %tr
                          %td Average
                          %td= t20_bt_average(@player.id)
                        %tr
                          %td Best Performance
                          %td= t20_best_batting(@player.id)
                  .col-sm-6
                    %h5 Bowling
                    %table.table.table-bordered
                      %tbody
                        %tr
                          %td Innings
                          %td= t20_bl_innings(@player.id)
                        %tr
                          %td Balls
                          %td= t20_bl_balls(@player.id)
                        %tr
                          %td Runs
                          %td= t20_bl_runs(@player.id)
                        %tr
                          %td Wickets
                          %td= t20_bl_wickets(@player.id)
                        %tr
                          %td Best Performance
                          %td= t20_best_bowling(@player.id)
              #odi.tab-pane.fade
                %section.narrow
                  %h3.bg-navy Player ODI Statistics
                  .text-center
                    %p 
                      Debut: 
                      - if @player.odi_debut?
                        %span.label.label-success 
                          #{@player.odi_debut.to_formatted_s(:long)}             
                    %p 
                      Matches Played: 
                      %span.label.label-success 
                        #{odi_matches(@player.id)}
                  .col-sm-6
                    %h5 Batting
                    %table.table.table-bordered
                      %tbody
                        %tr
                          %td Innings
                          %td= odi_bt_innings(@player.id)
                        %tr
                          %td Runs
                          %td= odi_bt_runs(@player.id)
                        %tr
                          %td Not out
                          %td= odi_bt_not_out(@player.id)
                        %tr
                          %td Average
                          %td= odi_bt_average(@player.id)
                        %tr
                          %td Best Performance
                          %td= odi_best_batting(@player.id)
                  .col-sm-6
                    %h5 Bowling
                    %table.table.table-bordered
                      %tbody
                        %tr
                          %td Innings
                          %td= odi_bl_innings(@player.id)
                        %tr
                          %td Balls
                          %td= odi_bl_balls(@player.id)
                        %tr
                          %td Runs
                          %td= odi_bl_runs(@player.id)
                        %tr
                          %td Wickets
                          %td= odi_bl_wickets(@player.id)
                        %tr
                          %td Best Performance
                          %td= odi_best_bowling(@player.id)
              #test.tab-pane.fade
                %section.narrow
                  %h3.bg-red Player Test Statistics
                  .text-center
                    %p 
                      Debut: 
                      - if @player.test_debut?
                        %span.label.label-success 
                          #{@player.test_debut.to_formatted_s(:long)}             
                    %p 
                      Matches Played: 
                      %span.label.label-success 
                        #{test_matches(@player.id)}                
                  .col-sm-6
                    %h5 Batting
                    %table.table.table-bordered
                      %tbody
                        %tr
                          %td Innings
                          %td= test_bt_innings(@player.id)
                        %tr
                          %td Runs
                          %td= test_bt_runs(@player.id)
                        %tr
                          %td Not out
                          %td= test_bt_not_out(@player.id)
                        %tr
                          %td Average
                          %td= test_bt_average(@player.id)
                        %tr
                          %td Best Performance
                          %td= test_best_batting(@player.id)
                  .col-sm-6
                    %h5 Bowling
                    %table.table.table-bordered
                      %tbody
                        %tr
                          %td Innings
                          %td= test_bl_innings(@player.id)
                        %tr
                          %td Balls
                          %td= test_bl_balls(@player.id)
                        %tr
                          %td Runs
                          %td= test_bl_runs(@player.id)
                        %tr
                          %td Wickets
                          %td= test_bl_wickets(@player.id)
                        %tr
                          %td Best Performance
                          %td= test_best_bowling(@player.id)
              #comment.tab-pane.fade
                %section.narrow
                  / Chat box
                  - if @player.comments.any?
                    .box.box-solid.box-success
                      .box-header
                        %i.fa.fa-comments-o
                        %h3.box-title Comments
                      #chat-box.box-body.chat
                        = render partial: 'comments/comment', collection: @player.comments

                  / /.box (chat box)
                  / quick email widget
                  .box.box-solid.box-primary
                    .box-header
                      %i.fa.fa-comment-o
                      %h3.box-title Leave a comment
                    .box-body
                      = render partial: 'comments/form'
              .clearfix
        .box-footer
          %p
            = link_to '<i class="fa fa-arrow-circle-left"></i>'.html_safe, players_path, :class => "btn btn-default", :title => "Back to Players"
            - if current_user.present? && @player.user_id == current_user.id
              = link_to '<i class="fa fa-edit"></i>'.html_safe, edit_player_path(@player), :class => 'btn btn-default', :title => "Edit player"
            
      %br