config/routes.rb
Mccs::Application.routes.draw do

  root to: "welcome#home"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
      controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :players do 
    resources :comments, only: [:create]
  end
  resources :matches
    get 'matches/:id/team_a_inning' => 'matches#team_a_inning', :as => :add_team_a_inning
    get 'matches/:id/team_b_inning' => 'matches#team_b_inning', :as => :add_team_b_inning
  resources :innings, only: [:new, :create]
  resources :venues
  resources :umpires
  resources :series
  resources :teams
  resources :team_flags, only: [:show]
  resources :clubs
  resources :club_flags, only: [:show]  

  resources :users, only: [:edit, :update]
  resources :authorizations, only: [:index, :show]

  namespace :admin do
    get 'dashboard/home' => "dashboard#home", as: :dashboard_home
    resources :dashboard, only: [:home]
    resources :authorizations, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :competition_type
  belongs_to :competition_overs_limit
  belongs_to :series

  belongs_to :team_a, :class_name => "Team"
  belongs_to :team_b, :class_name => "Team"

  belongs_to :user
  belongs_to :venue

  has_many :inning_extras, :dependent => :destroy
  accepts_nested_attributes_for :inning_extras, allow_destroy: true

  has_many :batsman_in_innings, :dependent => :destroy
  accepts_nested_attributes_for :batsman_in_innings, allow_destroy: true,
    reject_if: proc { |attributes| attributes['player_id'].blank? } 
  
  has_many :bowler_in_innings, :dependent => :destroy
  accepts_nested_attributes_for :bowler_in_innings, allow_destroy: true, 
    reject_if: proc { |attributes| attributes['player_id'].blank? } 

  has_many :umpires_in_matches, :dependent => :destroy
  has_many :umpires, through: :umpires_in_matches

  validates_presence_of :team_a_id, :team_b_id, :competition_type_id, :competition_overs_limit_id, 
        :team_won_toss, :team_choose_to, on: :create

  # def total_runs(team)
  #   runs = BatsmanInInning.where(:match_id => self.id, :team_id => team).sum("runs")
  #   extra_runs = InningExtra.find_by(:match_id => self.id, :team_id => team).total_extras
  #   total_runs = (runs + extra_runs)
  # end
  
  # def total_outs(team)
  #   BatsmanInInning.where("match_id = #{self.id} and team_id = #{team} and out_id != 7").count
  # end 
  
  # def total_overs(team)
  #   BowlerInInning.where(:match_id => self.id, :team_id => team).sum("overs")
  # end 
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :set_match, only: [:new_match, :team_a_inning, :team_b_inning, :edit, :update, :show, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    if current_user.present?
      @matches  = Match.where(:user_id => current_user.id)
    else
      @matches  = Match.all
    end
    @matches = Match.all
  end
  
  def new_match
  end
  
  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # GET /matches/1/edit
  def edit
  end

  def team_a_inning

  end

  def team_b_inning

  end
  
  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new(match_params)
    @match.user_id = current_user.id

    respond_to do |format|
      if @match.save
        if params[:match][:show].present?
          toast('success','Match was successfully created!')
          format.html { redirect_to @match }
          format.json { render action: 'new_match', status: :created, location: @match }
          format.js { render action: 'new_match', status: :created, location: @match }
        else    
          format.html { redirect_to @match, toast('success','Match was successfully created!') }
          format.json { render action: 'show', status: :created, location: @match }
        end        
      else
        format.html { render action: 'new' }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /matches/1
  # PATCH/PUT /matches/1.json
  def update
    respond_to do |format|
      if @match.update(match_params)
        format.html { redirect_to @match, notice: 'Match was successfully updated.' }
        format.json { head :no_content }
      else

        team = params[:match][:inning_extras_attributes]["0"][:team_id]     
        if @match.team_a_id = team
          format.html { render action: 'team_a_inning' }
          format.json { render json: @match.errors, status: :unprocessable_entity }
        elsif  @match.team_b_id = team 
          format.html { render action: 'team_b_inning' }
          format.json { render json: @match.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      if params[:show].present?
        @series = Series.find(@match.series_id) 
        toast('success','Match was successfully removed!')
        format.html { redirect_to @series }
        format.json { render action: 'show', status: :created, location: @series }
      else    
        format.html { redirect_to matches_url }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def match_params
      params.require(:match).permit(:team_a_id, :team_b_id, :series_id, :competition_type_id, :venue_id, :team_won_toss, :team_choose_to, :start_date, :end_date, :competition_overs_limit_id, :user_id, :umpire_ids => [],
        inning_extras_attributes: [:match_id, :team_id, :bye, :leg_bye, :wide, :no_ball, :id, :_destroy],
        batsman_in_innings_attributes: [:match_id, :team_id, :player_id, :runs, :balls, :fours, :sixes, :minutes, :out_id, :out_bowler_id, :out_fielder_id, :id, :_destroy],
        bowler_in_innings_attributes: [:player_id, :match_id, :team_id, :overs, :maiden_overs, :runs, :wickets, :id, :_destroy])
    end
end

app/helpers/matches_helper.rb
module MatchesHelper

  def Inning match, team
    if InningExtra.where(:match_id => match, :team_id => team).present? 
       true
    else
      false   
    end
  end

  def Summary match, team
    number_with_precision(total_runs(match, team), precision: 0) + "/#{total_outs(match, team)}"
  end

  def total_runs match, team
    runs = BatsmanInInning.where(:match_id => match, :team_id => team).sum("runs")
    extra_runs = InningExtra.find_by(:match_id => match, :team_id => team).total_extras
    total_runs = runs + extra_runs
  end
  
  def total_outs match, team
    BatsmanInInning.where("match_id = #{match} and team_id = #{team} and out_id != 7").count
  end 
  
  def total_overs match, team
    BowlerInInning.where(:match_id => match, :team_id => team).sum("overs")
  end

  def run_rate match, teamA, teamB
    total_runs(match, teamA).to_f/total_overs(match, teamB).to_f
  end

  def Results match, teamA, teamB
    @match = Match.find(match)

    if @match.team_won_toss == @match.team_a.name && @match.team_choose_to == "Batting First"
      if total_runs(@match.id, teamA) > total_runs(@match.id, teamB)
        runs_won_by = total_runs(@match.id, teamA) - total_runs(@match.id, teamB)
        result = "#{@match.team_a.name} won by #{number_with_precision(runs_won_by, precision: 0)} runs"
      elsif total_runs(@match.id, teamB) > total_runs(@match.id, teamA)
        wickets_won_by = 10 - total_outs(@match.id, teamB)
        result = "#{@match.team_b.name} won by #{wickets_won_by} wickets"
      end       
    elsif @match.team_won_toss == @match.team_a.name && @match.team_choose_to == "Bowling First"
      if total_runs(@match.id, teamA) > total_runs(@match.id, teamB)
        wickets_won_by = 10 - total_outs(@match.id, teamA)
        result = "#{@match.team_a.name} won by #{wickets_won_by} wickets"
      elsif total_runs(@match.id, teamB) > total_runs(@match.id, teamA)
        runs_won_by = total_runs(@match.id, teamB) - total_runs(@match.id, teamA)
        result = "#{@match.team_b.name} won by #{number_with_precision(runs_won_by, precision: 0)} runs"      
      end      
    elsif @match.team_won_toss == @match.team_b.name && @match.team_choose_to == "Batting First"
      if total_runs(@match.id, teamB) > total_runs(@match.id, teamA)
        runs_won_by = total_runs(@match.id, teamB) - total_runs(@match.id, teamA)
        result = "#{@match.team_b.name} won by #{number_with_precision(runs_won_by, precision: 0)} runs"
      elsif total_runs(@match.id, teamA) > total_runs(@match.id, teamB)
        wickets_won_by = 10 - total_outs(@match.id, teamA)
        result = "#{@match.team_a.name} won by #{wickets_won_by} wickets"
      end
    elsif @match.team_won_toss == @match.team_b.name && @match.team_choose_to == "Bowling First"
      if total_runs(@match.id, teamB) > total_runs(@match.id, teamA)
        wickets_won_by = 10 - total_outs(@match.id, teamB)
        result = "#{@match.team_b.name} won by #{wickets_won_by} wickets"
      elsif total_runs(@match.id, teamA) > total_runs(@match.id, teamB)
        runs_won_by = total_runs(@match.id, teamA) - total_runs(@match.id, teamB)
        result = "#{@match.team_a.name} won by #{number_with_precision(runs_won_by, precision: 0)} runs"
      end  
    end

  end  
end

app/views/matches/_form.html.haml
= bootstrap_form_for @match do |f|
  - if @match.errors.any?
    #error_explanation
      %h2= "#{pluralize(@match.errors.count, "error")} prohibited this match from being saved:"
      %ul
        - @match.errors.full_messages.each do |msg|
          %li= msg

  = f.number_field :series_id
  = f.number_field :competition_type_id

  = f.number_field :venue_id

  = f.number_field :team_a_id

  = f.number_field :team_b_id

  = f.text_field :team_won_toss

  = f.text_field :team_choose_to
  = f.text_field :start_date
  = f.text_field :end_date
  
  %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#umpires", :class => 'btn btn-default'}
    Select two Umpires:
  #umpires.panel-collapse.collapse
    = f.collection_check_boxes :umpire_ids, Umpire.all, :id, :name, hide_label: true
  
  :javascript
    var countChecked = function() {
      var n = $( 'input[name="match[umpire_ids][]"]:checked' ).length;
      if (n >= 2) {
        Command: toastr.warning("Umpire selection can only be two");
        $( 'input[name="match[umpire_ids][]"]' ).not(':checked').attr("disabled",true);
      }
      else {
        $( 'input[name="match[umpire_ids][]"]' ).not(':checked').attr("disabled",false);
      }
    };
    countChecked();
 
    $( 'input[name="match[umpire_ids][]"]' ).on( "click", countChecked ); 
  
  = f.submit 'Save'

app/views/matches/_scorecard_a.html.haml
.panel.panel-default
  .panel-heading
    %h4.panel-title
      %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#teamA"}
        = @match.team_a.name
        Inning (Run Rate #{number_with_precision(run_rate(@match.id, @match.team_a_id, @match.team_b_id), precision: 2)})
  #teamA.panel-collapse.collapse.in
    .panel-body
      %h5 Batting
      .table-responsive
        %table.table.table-bordered
          %thead.scorecard_batting_head
            %tr
              %th Batting
              %th Out Desc
              %th R
              %th B
              %th 4s
              %th 6s
              %th SR
          %tbody
            - @match.batsman_in_innings.where(:team_id => @match.team_a_id ).each do |t|
              %tr
                %td= t.player.name
                %td= t.out_def(t.out_id)
                %td= t.runs
                %td= t.balls
                %td= t.fours
                %td= t.sixes
                %td= number_with_precision(t.strike_rate, precision: 2)
          %tbody
            %tr
              %td 
                %b Extras
              %td
              - @match.inning_extras.where(:team_id => @match.team_a_id ).each do |i|
                %td{:colspan => "5"}
                  %b 
                    = i.total_extras.round 
                    (b - #{i.bye}, w - #{i.wide}, nb - #{i.no_ball}, lb - #{i.leg_bye})
            %tr
              %td
                %b Total
              %td
              %td{:colspan => "5"}
                %b
                  = number_with_precision(total_runs(@match.id, @match.team_a_id), precision: 0)
                  (#{total_overs(@match.id, @match.team_b_id)} - overs, #{total_outs(@match.id, @match.team_a_id)} - wickets)
      .table-responsive
        %h5 Bowling
        %table.table.table-bordered
          %thead.scorecard_bowling_head
            %tr
              %th Bowler
              %th Overs
              %th Maiden
              %th Runs
              %th Wickets
              %th E/R
          %tbody
            - @match.bowler_in_innings.where(:team_id => @match.team_b_id ).each do |t|
              %tr
                %td= t.player.name
                %td= t.overs
                %td= t.maiden_overs
                %td= t.runs
                %td= t.wickets
                %td= number_with_precision(t.bowler_econ, precision: 2)

app/views/matches/_sidenavbar.html.haml
/ sidebar: style can be found in sidebar.less
%section.sidebar
  / sidebar menu: : style can be found in sidebar.less
  %ul.sidebar-menu
    %li
      %a{href: root_path}
        %i.fa.fa-home
        %span Home
    %li
      %a{href: clubs_path}
        %i.fa.fa-star
        %span Clubs
    %li
      %a{href: teams_path}
        %i.fa.fa-flag
        %span Teams
    %li
      %a{href: series_index_path}
        %i.fa.fa-trophy
        %span Series
    %li.active
      %a{href: matches_path}
        %i.fa.fa-maxcdn
        %span Matches
    %li
      %a{href: players_path}
        %i.fa.fa-group
        %span Players
    %li
      %a{href: umpires_path}
        %i.ion.ion-android-contacts
        %span Umpires
    %li
      %a{href: venues_path}
        %i.fa.fa-umbrella
        %span Venues
    %li.social
      %span
        #{social_share_button_tag("MyClubCricketStats", :url => request.original_url, :image => "http://www.elphax.com/assets/images/my-club-cricket-stats.png", desc: "MyClubCricketStats is a club cricket statics management application where users can create/manage the Clubs, Teams, and Players. MyClubCricketStats will calculate and populates each player and team stats after entering and saving the data.")}
/ /.sideba

app/views/matches/new.html.haml
%h1 New match

= render 'form'

= link_to 'Back', matches_path

app/views/matches/new_match.js.haml
$('#new_match_modal').modal_success();

app/views/matches/show.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Scorecard
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home  
        %li.active
          %a{:href => matches_path}
            %i.fa.fa-maxcdn
            Matches
    / /.content-header
    %section.content
      .match_info_box
        .row#result
          - if Inning(@match.id, @match.team_a_id) && Inning(@match.id, @match.team_b_id)
            %h3= Results(@match.id, @match.team_a_id, @match.team_b_id)
          .col-xs-6.text-right
            = image_tag "teams/#{@match.team_a.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
            %h3= @match.team_a.name
            
            - if Inning(@match.id, @match.team_a_id)
              %h4= Summary(@match.id, @match.team_a_id)
              %h5 Run Rate: #{number_with_precision(run_rate(@match.id, @match.team_a_id, @match.team_b_id), precision: 2)}            
              %h5 Overs: #{total_overs(@match.id, @match.team_b_id)}/#{@match.competition_overs_limit.overs}
          .col-xs-6.text-left
            = image_tag "teams/#{@match.team_b.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
            %h3= @match.team_b.name
            - if Inning(@match.id, @match.team_b_id)
              %h4= Summary(@match.id, @match.team_b_id)
              %h5 Run Rate: #{number_with_precision(run_rate(@match.id, @match.team_b_id, @match.team_a_id), precision: 2)} 
              %h5 Overs: #{total_overs(@match.id, @match.team_a_id)}/#{@match.competition_overs_limit.overs} 
      .box.box-default
        .box-header
          %h3.box-title Match Details
        .box-body
          %p 
            %b Toss: &nbsp;
            #{@match.team_won_toss} won the toss and choose to #{@match.team_choose_to}!  
          %p 
            %b Venue: &nbsp;
            #{@match.venue.details}
          %p 
            %b Umpires: &nbsp;
            - @match.umpires.each do |u|
              #{u.name} &nbsp;         

          #accordion.panel-group
            = link_to "Enter Innings Detail for #{@match.team_a.name}", add_team_a_inning_path(@match.id, :team => @match.team_a_id), :class => 'btn btn-primary' if !Inning(@match.id, @match.team_a_id)
            = link_to "Enter Innings Detail for #{@match.team_b.name}", add_team_b_inning_path(@match.id, :team => @match.team_b_id), :class => 'btn btn-primary' if !Inning(@match.id, @match.team_b_id)
            %br
            = render "scorecard_a" if Inning(@match.id, @match.team_a_id)
            = render "scorecard_b" if Inning(@match.id, @match.team_b_id)

app/views/matches/team_a_inning.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Scorecard Editing
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home  
        %li.active
          %a{:href => matches_path}
            %i.fa.fa-maxcdn
            Matches
    / /.content-header
    %section.content   
      .match_info_box
        %h4
          = @match.team_a.name
          = image_tag "teams/#{@match.team_a.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
          %span.badge vs
          = image_tag "teams/#{@match.team_b.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
          = @match.team_b.name

      .box.box-default
        .box-header
          %h3.box-title 
            = @match.team_a.name
            Inning
        .box-body
          :css
            select {
              width: 100px !important;
            }
            .form-group {
              margin-bottom: 0px !important;
            }

          = bv_form_for @match do |f|
            .row
              .col-lg-12
                %h4.great Batting
                %section.table-responsive.count
                  %table.table.table-bordered
                    %thead.batting_head
                      %tr
                        %th.text-center No
                        %th Player
                        %th{:colspan => "3"} Out Description (out, fielder, bowler)
                        %th Runs
                        %th Balls
                        %th 4s
                        %th 6s
                    %tbody.fixed_width
                      - bt = 1
                      - 11.times do
                        = f.fields_for :batsman_in_innings, @match.batsman_in_innings.build do |batting|
                          %tr
                            = batting.hidden_field(:team_id, :value => "#{@match.team_a_id}")
                            %td.text-center
                              %span.badge= bt
                            %td= batting.collection_select :player_id,  Player.where(:team_id => @match.team_a_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_id, Out.all ,:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_fielder_id, Player.where(:team_id => @match.team_b_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_bowler_id, Player.where(:team_id => @match.team_b_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.text_field :runs, hide_label: true, :placeholder => "000", :style => 'width: 50px'
                            %td= batting.text_field :balls, hide_label: true, :placeholder => "000", :style => 'width: 50px'
                            %td= batting.text_field :fours, hide_label: true, :placeholder => "00", :style => 'width: 42px'
                            %td= batting.text_field :sixes, hide_label: true, :placeholder => "00", :style => 'width: 42px'
                          - bt = bt + 1
            %hr
            .row
              .col-lg-8
                %h4.great Bowling
                %section.table-responsive.count
                  %table.table.table-bordered
                    %thead.bowling_head
                      %tr
                        %th.text-center No
                        %th Name
                        %th overs
                        %th maiden overs
                        %th runs
                        %th wickets
                    %tbody.fixed_width
                      - bl = 1
                      - 7.times do
                        = f.fields_for :bowler_in_innings, @match.bowler_in_innings.build do |bowling|
                          %tr
                            = bowling.hidden_field(:team_id, :value => "#{@match.team_b_id}")
                            %td.text-center
                              %span.badge= bl
                            %td= bowling.collection_select :player_id, Player.where(:team_id => @match.team_b_id ), :id, :name, :prompt => "select", hide_label: true
                            %td= bowling.text_field :overs, hide_label: true,:placeholder => "00", :style => 'width: 50px'
                            %td= bowling.text_field :maiden_overs, hide_label: true,:placeholder => "0", :style => 'width: 42px'
                            %td= bowling.text_field :runs,  hide_label: true,:placeholder => "000", :style => 'width: 50px'
                            %td= bowling.text_field :wickets, hide_label: true,:placeholder => "0", :style => 'width: 42px'
                          - bl = bl + 1
              .col-lg-4
                %h4.great Extras
                .table-responsive
                  %table.table.table-bordered
                    %thead.extra_head
                      %tr
                        %th Bye
                        %th Leg Bye
                        %th Wide
                        %th No Ball
                    %tbody.fixed_width
                      = f.fields_for :inning_extras, @match.inning_extras.build do |extras|
                        %tr
                          = extras.hidden_field(:team_id, :value => "#{@match.team_a_id}")
                          %td= extras.text_field :bye, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :leg_bye, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :wide, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :no_ball, hide_label: true, :style => 'width: 42px', :placeholder => "00"
          
            %hr/
            .row
              .col-lg-12
                %span
                  = f.submit 'Submit', :class => 'btn btn-primary pull-right', id: 'scorecard'
                  = link_to '<i class="fa fa-arrow-circle-left"></i> Cancel'.html_safe, match_path(@match.id), :class => 'btn btn-default', :title => "Back to Scorecard"

app/views/matches/team_b_inning.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Scorecard Editing
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home  
        %li.active
          %a{:href => matches_path}
            %i.fa.fa-maxcdn
            Matches
    / /.content-header
    %section.content   
      .match_info_box
        %h4
          = @match.team_a.name
          = image_tag "teams/#{@match.team_a.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
          %span.badge vs
          = image_tag "teams/#{@match.team_b.team_flag.file_name}", :class => 'flag_small img-thumbnail-circle'
          = @match.team_b.name

      .box.box-default
        .box-header
          %h3.box-title 
            = @match.team_b.name
            Inning
        .box-body
          :css
            select {
              width: 100px !important;
            }
            .form-group {
              margin-bottom: 0px !important;
            }

          = bv_form_for @match do |f|
            .row
              .col-lg-12
                %h4.great Batting
                %section.table-responsive.count
                  %table.table.table-bordered
                    %thead.batting_head
                      %tr
                        %th.text-center No
                        %th Player
                        %th{:colspan => "3"} Out Description (out, fielder, bowler)
                        %th Runs
                        %th Balls
                        %th 4s
                        %th 6s
                    %tbody.fixed_width
                      - bt = 1
                      - 11.times do
                        = f.fields_for :batsman_in_innings, @match.batsman_in_innings.build do |batting|
                          %tr
                            = batting.hidden_field(:team_id, :value => "#{@match.team_b_id}")
                            %td.text-center
                              %span.badge= bt
                            %td= batting.collection_select :player_id,  Player.where(:team_id => @match.team_b_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_id, Out.all ,:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_fielder_id, Player.where(:team_id => @match.team_a_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.collection_select :out_bowler_id, Player.where(:team_id => @match.team_a_id ),:id, :name, :prompt => "select", hide_label: true
                            %td= batting.text_field :runs, hide_label: true, :placeholder => "000", :style => 'width: 50px'
                            %td= batting.text_field :balls, hide_label: true, :placeholder => "000", :style => 'width: 50px'
                            %td= batting.text_field :fours, hide_label: true, :placeholder => "00", :style => 'width: 42px'
                            %td= batting.text_field :sixes, hide_label: true, :placeholder => "00", :style => 'width: 42px'
                          - bt = bt + 1
            %hr
            .row
              .col-lg-8
                %h4.great Bowling
                %section.table-responsive.count
                  %table.table.table-bordered
                    %thead.bowling_head
                      %tr
                        %th.text-center No
                        %th Name
                        %th overs
                        %th maiden overs
                        %th runs
                        %th wickets
                    %tbody.fixed_width
                      - bl = 1
                      - 7.times do
                        = f.fields_for :bowler_in_innings, @match.bowler_in_innings.build do |bowling|
                          %tr
                            = bowling.hidden_field(:team_id, :value => "#{@match.team_a_id}")
                            %td.text-center
                              %span.badge= bl
                            %td= bowling.collection_select :player_id, Player.where(:team_id => @match.team_a_id ), :id, :name, :prompt => "select", hide_label: true
                            %td= bowling.text_field :overs, hide_label: true,:placeholder => "00", :style => 'width: 50px'
                            %td= bowling.text_field :maiden_overs, hide_label: true,:placeholder => "0", :style => 'width: 42px'
                            %td= bowling.text_field :runs,  hide_label: true,:placeholder => "000", :style => 'width: 50px'
                            %td= bowling.text_field :wickets, hide_label: true,:placeholder => "0", :style => 'width: 42px'
                          - bl = bl + 1
              .col-lg-4
                %h4.great Extras
                .table-responsive
                  %table.table.table-bordered
                    %thead.extra_head
                      %tr
                        %th Bye
                        %th Leg Bye
                        %th Wide
                        %th No Ball
                    %tbody.fixed_width
                      = f.fields_for :inning_extras, @match.inning_extras.build do |extras|
                        %tr
                          = extras.hidden_field(:team_id, :value => "#{@match.team_b_id}")
                          %td= extras.text_field :bye, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :leg_bye, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :wide, hide_label: true, :style => 'width: 42px', :placeholder => "00"
                          %td= extras.text_field :no_ball, hide_label: true, :style => 'width: 42px', :placeholder => "00"
          
            %hr
            .row
              .col-lg-12
                %span
                  = f.submit 'Submit', :class => 'btn btn-primary pull-right', id: 'scorecard'
                  = link_to '<i class="fa fa-arrow-circle-left"></i> Cancel'.html_safe, match_path(@match.id), :class => 'btn btn-default', :title => "Back to Scorecard"