config/routes.rb
Mccs::Application.routes.draw do

  root to: "welcome#home"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
      controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :players do 
    resources :comments, only: [:create]
  end
  resources :matches
    get 'matches/:id/team_a_inning' => 'matches#team_a_inning', :as => :add_team_a_inning
    get 'matches/:id/team_b_inning' => 'matches#team_b_inning', :as => :add_team_b_inning
  resources :innings, only: [:new, :create]
  resources :venues
  resources :umpires
  resources :series
  resources :teams
  resources :team_flags, only: [:show]
  resources :clubs
  resources :club_flags, only: [:show]  

  resources :users, only: [:edit, :update]
  resources :authorizations, only: [:index, :show]

  namespace :admin do
    get 'dashboard/home' => "dashboard#home", as: :dashboard_home
    resources :dashboard, only: [:home]
    resources :authorizations, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
      :recoverable, :rememberable, :trackable, :validatable, :omniauthable
  validates_presence_of :name
  has_many :authorizations
  has_many :clubs
  has_many :teams
  has_many :players
  has_many :matches

  def self.new_with_session(params,session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"],without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def self.from_omniauth(auth, current_user)
    authorization = Authorization.where(:provider => auth.provider, :uid => auth.uid.to_s, :token => auth.credentials.token, :secret => auth.credentials.secret).first_or_initialize
    if authorization.user.blank?
      user = current_user.nil? ? User.where('email = ?', auth["info"]["email"]).first : current_user
      if user.blank?
        user = User.new
        user.password = Devise.friendly_token[0,10]
        user.name = auth.info.name
        if auth.provider == "twitter"
          user.email = auth.info.nickname + '_' + (0...8).map { (65 + rand(26)).chr }.join + '@gmail.com'
        else
          user.email = auth.info.email
        end
          auth.provider == "twitter" ?  user.save(:validate => false) :  user.save
      end
      authorization.username = auth.info.nickname
      authorization.user_id = user.id
      authorization.save
    end
    authorization.user
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :destroy]
  before_action :set_user, only: [:show, :destroy]
  
  def index
    @users = User.all
  end

  def show
  end

  def destroy
    @user.destroy
    respond_to do |format|
      toast('success',"User '#{@user.name}' removed!")
      format.html { redirect_to admin_users_path }
    end
  end

  private
    def set_user
      @user = User.find(params[:id])
    end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def edit
  end

  def update
    if @user.update(user_params)
      toast('success','User was successfully updated!')
      redirect_to root_path and return
    else
      render action: 'edit'
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end
    
    def user_params
      params.require(:user).permit(:name, :email)
    end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/index.html.haml
/ Content Header (Page header)
.main-content  
  %section.content-header
    %h1
      Dashboard
      %small Control panel
    %ol.breadcrumb
      %li
        %a{:href => root_path}
          %i.fa.fa-home
          Home
      %li
        %a{:href => admin_dashboard_home_path}
          %i.fa.fa-dashboard
          Dashboard
      %li.active Users
  %section.box.box-default
    .box-body       
      %h3 Users

      .table-responsive
        %table.table.table-hover
          %thead.bg-blue
            %tr
              %th Name
              %th Email
              %th Last login
              %th Created on
              %th Updated on
              %th  
          %tbody
            - @users.each do |user|
              %tr
                %td= user.name
                %td= user.email 
                %td= user.last_sign_in_at.to_formatted_s(:long)
                %td= user.created_at.to_formatted_s(:long)
                %td= user.updated_at.to_formatted_s(:long)
                %td.btn-group
                  = link_to '<i class="fa fa-eye"></i>'.html_safe, admin_user_path(user), class: "btn btn-default btn-sm"
                  = link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm'
    .box-footer  

app/views/admin/users/show.html.haml
/ Content Header (Page header)
.main-content  
  %section.content-header
    %h1
      Dashboard
      %small Control panel
    %ol.breadcrumb
      %li
        %a{:href => root_path}
          %i.fa.fa-home
          Home
      %li
        %a{:href => admin_dashboard_home_path}
          %i.fa.fa-dashboard
          Dashboard
      %li.active Users
  %section.box.box-default
    .box-body       
      .row
        / Users Info
        .col-lg-6.col-xs-6
          %h3 Users Info
          %section.box.box-primary
            .box-body           
              %table.table.table-striped.table-bordered
                %thead
                  %tr
                    %th.bold Fields
                    %th.bold Description
                %tbody
                  %tr
                    %td.bold Name:
                    %td= @user.name
                  %tr
                    %td.bold Email:
                    %td= @user.email
                  %tr
                    %td.bold Last Login:
                    %td= @user.last_sign_in_at.to_formatted_s(:long)
                  %tr
                    %td.bold Last Login IP:
                    %td= @user.last_sign_in_ip
                  %tr
                    %td.bold Created on:
                    %td= @user.created_at.to_formatted_s(:long)
                  %tr
                    %td.bold Update on:
                    %td= @user.updated_at.to_formatted_s(:long)       
        / Users Authorizations
        .col-lg-6.col-xs-6
          %h3 Users Authorizations
          %section.box.box-success
            .box-body               
              .table-responsive
                %table.table.table-hover
                  %thead
                    %tr
                      %th Provider
                      %th Uid
                      %th Last Authorized
                      %th 
                  %tbody
                    - @user.authorizations.each do |user_auth|
                      %tr
                        %td= user_auth.provider
                        %td= user_auth.uid
                        %td= user_auth.created_at.to_formatted_s(:long)
                        %td= link_to '<i class="fa fa-trash-o"></i>'.html_safe, admin_authorization_path(user_auth, :back_to => @user.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn btn-default btn-sm' 
    .box-footer
      = link_to '<i class="fa fa-arrow-circle-left"></i> Back'.html_safe, admin_users_path, :class => 'btn btn-default' 