config/routes.rb
Mccs::Application.routes.draw do

  root to: "welcome#home"
  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, 
      controllers: {omniauth_callbacks: "omniauth_callbacks"}

  resources :players do 
    resources :comments, only: [:create]
  end
  resources :matches
    get 'matches/:id/team_a_inning' => 'matches#team_a_inning', :as => :add_team_a_inning
    get 'matches/:id/team_b_inning' => 'matches#team_b_inning', :as => :add_team_b_inning
  resources :innings, only: [:new, :create]
  resources :venues
  resources :umpires
  resources :series
  resources :teams
  resources :team_flags, only: [:show]
  resources :clubs
  resources :club_flags, only: [:show]  

  resources :users, only: [:edit, :update]
  resources :authorizations, only: [:index, :show]

  namespace :admin do
    get 'dashboard/home' => "dashboard#home", as: :dashboard_home
    resources :dashboard, only: [:home]
    resources :authorizations, only: [:index, :destroy]
    resources :users, only: [:index, :show, :destroy]
  end
  
end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :competition_type
  belongs_to :competition_overs_limit
  belongs_to :series

  belongs_to :team_a, :class_name => "Team"
  belongs_to :team_b, :class_name => "Team"

  belongs_to :user
  belongs_to :venue

  has_many :inning_extras, :dependent => :destroy
  accepts_nested_attributes_for :inning_extras, allow_destroy: true

  has_many :batsman_in_innings, :dependent => :destroy
  accepts_nested_attributes_for :batsman_in_innings, allow_destroy: true,
    reject_if: proc { |attributes| attributes['player_id'].blank? } 
  
  has_many :bowler_in_innings, :dependent => :destroy
  accepts_nested_attributes_for :bowler_in_innings, allow_destroy: true, 
    reject_if: proc { |attributes| attributes['player_id'].blank? } 

  has_many :umpires_in_matches, :dependent => :destroy
  has_many :umpires, through: :umpires_in_matches

  validates_presence_of :team_a_id, :team_b_id, :competition_type_id, :competition_overs_limit_id, 
        :team_won_toss, :team_choose_to, on: :create

  # def total_runs(team)
  #   runs = BatsmanInInning.where(:match_id => self.id, :team_id => team).sum("runs")
  #   extra_runs = InningExtra.find_by(:match_id => self.id, :team_id => team).total_extras
  #   total_runs = (runs + extra_runs)
  # end
  
  # def total_outs(team)
  #   BatsmanInInning.where("match_id = #{self.id} and team_id = #{team} and out_id != 7").count
  # end 
  
  # def total_overs(team)
  #   BowlerInInning.where(:match_id => self.id, :team_id => team).sum("overs")
  # end 
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_series, only: [:new_series, :show, :destroy]

  # GET /series
  # GET /series.json
  def index
    if current_user.present?
      @series_all = Series.where(:user_id => current_user.id)
    else
      @series_all = Series.all
    end
    @series = Series.new
  end

  def new_series
  end

  # GET /series/1
  # GET /series/1.json
  def show
  end

  # GET /series/new
  def new
    @series = Series.new
  end

  # POST /series
  # POST /series.json
  def create
    @series = Series.new(series_params)
    @series.user_id = current_user.id
    
    respond_to do |format|
      if @series.save
        toast('success','Series was successfully created!')
        format.html { redirect_to @series }
        format.json { render action: 'show', status: :created, location: @series }
        format.js   { render action: 'new_series', status: :created, location: @series}
      else
        format.html { render action: 'new' }
        format.json { render json: @series.errors, status: :unprocessable_entity }
        format.js   { render json: @series.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /series/1
  # DELETE /series/1.json
  def destroy
    @series.destroy
    respond_to do |format|
      format.html { redirect_to series_index_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_series
      @series = Series.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def series_params
      params.require(:series).permit(:name, :start_date, :end_date, :user_id)
    end
end

app/helpers/series_helper.rb
module SeriesHelper
  def link_to_add_match_fields(name, f, match)
    new_object = f.object.send(match).klass.new
    id = new_object.object_id
    fields = f.fields_for(match, new_object, child_index: id) do |builder|
      render(match.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_match_fields btn btn-success", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/series/_form.html.haml
.row
  .col-sm-8
    - modal ||= false
    - remote = modal ? true : false  
    = bv_form_for(@series, remote: remote, html: {role: :form, 'data-model' => 'series'}) do |f|
      = f.text_field :name, required: true
      = f.text_field :start_date, :class => 'series_datepicker', :placeholder => "mmmm dd, yyyy", append: "<i class='fa fa-calendar'></i>".html_safe, required: true
      = f.text_field :end_date, :class => 'series_datepicker', :placeholder => "mmmm dd, yyyy", append: "<i class='fa fa-calendar'></i>".html_safe, required: true
      = f.hidden_field :user_id
      = f.submit 'Submit', :class => 'btn btn-primary' 
    :Javascript
      $(document).ready(function() { 
        $(document).bind('ajaxError', 'form#new_series', function(event, jqxhr, settings, exception){

          // note: jqxhr.responseJSON undefined, parsing responseText instead
          $(event.data).render_form_errors( $.parseJSON(jqxhr.responseText) );

        });

        $('#series_start_date, #series_end_date').change(function() {
          $('#new_series').bootstrapValidator('revalidateField', 'series[start_date]');
          $('#new_series').bootstrapValidator('revalidateField', 'series[end_date]');
        });

        $('#new_series')
            .bootstrapValidator()
              .on('success.form.bv', function(e) {
                  // Called when the form is valid
                  var $form = $(e.target);
                  if ($form.data('remote')) {
                      e.preventDefault();
                      return false;
                  }
              })
              .on('submit', function(e) {
                  var $form = $(e.target);
                  if ($form.data('remote')) {
                      var numInvalidFields = $form.data('bootstrapValidator').getInvalidFields().length;
                      if (numInvalidFields) {
                          e.preventDefault();
                          return false;
                      }
                  }
              });
      });
      (function($) {

        $.fn.modal_success = function(){
          // close modal
          this.modal('hide');

          // clear form input elements
          // todo/note: handle textarea, select, etc
          this.find('form input[type="text"]').val('');

          // clear error state
          this.clear_previous_errors();

          // reload page 
          location.reload();
        };

        $.fn.render_form_errors = function(errors){

          $form = this;
          this.clear_previous_errors();
          model = this.data('model');

          // show error messages in input form-group help-block
          $.each(errors, function(field, messages){
            $input = $('input[name="' + model + '[' + field + ']"]');
            $input.closest('.form-group').addClass('has-error').find('.help-block').html( messages.join(' & ') );
          });

        };

        $.fn.clear_previous_errors = function(){
          $('.form-group.has-error', this).each(function(){
            $('.help-block', $(this)).html('');
            $(this).removeClass('has-error');
          });
        }

      }(jQuery));       

app/views/series/_match_form.html.haml
- modal ||= false
- remote = modal ? true : false  
= bv_form_for(Match.new, remote: remote, html: {role: :form, 'data-model' => 'match'}) do |f|
  .row
    .col-sm-5
      .panel.panel-default
        .panel-heading
          %h3.panel-title Team A
        .panel-body.team-pic-box
          = image_tag 'teams/default-team.png', :class => 'image_responsive img-thumbnail-circle', :id =>"teamA"
          %br/
          %br/
          = f.collection_select :team_a_id, Team.where(:user_id => current_user.id), :id, :name, hide_label: true, :prompt => "select", :class => 'select'
    .col-sm-2
      .vs-box
        %span.vs vs
    .col-sm-5
      .panel.panel-default
        .panel-heading
          %h3.panel-title Team B
        .panel-body.team-pic-box
          = image_tag 'teams/default-team.png', :class => 'image_responsive img-thumbnail-circle', :id =>"teamB"
          %br/
          %br/
          = f.collection_select :team_b_id, Team.where(:user_id => current_user.id), :id, :name, hide_label: true, :prompt => "select", :class => 'select'
  %hr        
  .row
    .col-sm-6
      = f.collection_select :competition_type_id, CompetitionType.all, :id, :name, label: "Competition Type", :prompt => "select", :class => 'select'
    .col-sm-6  
      = f.collection_select :competition_overs_limit_id, CompetitionOversLimit.all, :id, :overs, label: "Competition Overs", :prompt => "select", :class => 'select'
  .row
    .col-sm-6
      = f.select :team_won_toss, [["TeamA"], ["TeamB"]], label: "Team Won Toss", :prompt => "select", :class => 'select'
    .col-sm-6  
      = f.select :team_choose_to, [["Batting First"], ["Bowling First"]], label: "Team Choose To", :prompt => "select", :class => 'select'
  .row
    .col-sm-6
      = f.collection_select :venue_id, Venue.where(:user_id => current_user.id), :id, :name_with_details, label: "Venue", :prompt => "select", :class => 'select'
    .col-sm-6
      .form-group
        %label#umpire_label Umpires
        %a{"data-parent" => "#accordion", "data-toggle" => "collapse", :href => "#umpires_selection", :class => 'btn btn-block btn-success btn-flat'}
          Select two Umpires:
        #umpires_selection.panel-collapse.collapse
          = f.collection_check_boxes :umpire_ids, Umpire.all, :id, :name, hide_label: true, :class => 'icheck-me'      
  .row
    .col-sm-6
      = f.text_field :start_date, :class => 'series_datepicker', :placeholder => "mmmm dd, yyyy", append: "<i class='fa fa-calendar'></i>".html_safe, required: true
    #end-date.col-sm-6  
      = f.text_field :end_date, :class => 'series_datepicker', :placeholder => "mmmm dd, yyyy", append: "<i class='fa fa-calendar'></i>".html_safe
  .row
    .col-sm-12
      = f.hidden_field :series_id, value: series
      = f.hidden_field :user_id
      = f.hidden_field "show", value: "series_show"
      = f.submit 'Submit', :class => 'btn btn-primary pull-right'        
    :Javascript
      $(document).ready(function() {
        var countChecked = function() {
          var n = $( 'input[name="match[umpire_ids][]"]:checked' ).length;
          
          if (n >= 2) {
            $( 'input[name="match[umpire_ids][]"]' ).not(':checked').attr("disabled",true);
            validationSelect();
          }
          else {
            $( 'input[name="match[umpire_ids][]"]' ).not(':checked').attr("disabled",false);

          }
        };
        countChecked();
     
        $( 'input[name="match[umpire_ids][]"]' ).on( "click", countChecked ); 

        $(document).bind('ajaxError', 'form#new_match', function(event, jqxhr, settings, exception){

          // note: jqxhr.responseJSON undefined, parsing responseText instead
          $(event.data).render_form_errors( $.parseJSON(jqxhr.responseText) );

        });
        // client-side validation
        $('input[name="commit"]').click(function() {
          validationSelect();
        });
        
        $('#match_start_date, #match_end_date, #match_team_a_id, #match_team_b_id, #match_competition_overs_limit_id, #match_team_won_toss, #match_team_choose_to, #match_venue_id').change(function() {
          validationSelect();
          $('#new_match').bootstrapValidator('revalidateField', 'match[start_date]');
        });
        
        $('#match_end_date').change(function() {
          if ($('#match_end_date').attr('required')) {
            var v = $('#match_end_date').val();
            if ( v.length != 0 ) {
              $('#end-date > :first').removeClass('has-feedback has-error');
              $('#end-date > :first').addClass('has-success');
            }
            else {
              $('#end-date > :first').removeClass('has-success');
              $('#end-date > :first').addClass('has-feedback has-error');
            } 
          
          }
          $('#new_match').bootstrapValidator('revalidateField', 'match[start_date]');
        });   
        $('#match_competition_type_id').change(function() {
          var value = $(this).find('option:selected').text();
          var v = $('#match_end_date').val();
          if ( v.length == 0 ) {
            switch (value) {
              case "Test 3 Days":
                  $('#match_end_date').attr('required', "required");
                  $('#end-date > :first').addClass('has-feedback has-error');           
                  break;
              case "Test 5 Days":
                  $('#match_end_date').attr('required', "required");
                  $('#end-date > :first').addClass('has-feedback has-error');          
                  break;
              default:
                  if ($('#match_end_date').attr('required')) {
                    $('#match_end_date').removeAttr('required');
                    $('#end-date > :first').removeClass('has-feedback has-error');
                  }            
            }
          } else {
            switch (value) {
              case "One Day":
                  $('#match_end_date').val('');
                  $('#end-date > :first').removeClass('has-success');         
                  break;
              case "T20":
                  $('#match_end_date').val('');
                  $('#end-date > :first').removeClass('has-success');          
                  break;
              default:
                             
            }

          }

          validationSelect(); 
        });
        function validationSelect() {
          var ta = $('#match_team_a_id option:selected').text();
          if (ta == "select") {
            $('#match_team_a_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_team_a_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_a_id').parent('.form-group').addClass('has-success');
          }           
          var tb = $('#match_team_b_id option:selected').text();
          if (tb == "select") {
            $('#match_team_b_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_team_b_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_b_id').parent('.form-group').addClass('has-success');
          }
          if ( ta == tb ) {
            Command: toastr.error("Team vs Team selections can't be same!");
            $('#match_team_a_id').parent('.form-group').addClass('has-feedback has-error');
            $('#match_team_b_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_team_a_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_a_id').parent('.form-group').addClass('has-success');
            $('#match_team_b_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_b_id').parent('.form-group').addClass('has-success');
          }
          var ct = $('#match_competition_type_id option:selected').text();
          if (ct == "select") {
            $('#match_competition_type_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_competition_type_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_competition_type_id').parent('.form-group').addClass('has-success');
          }
          var co = $('#match_competition_overs_limit_id option:selected').text();
          if (co == "select") {
            $('#match_competition_overs_limit_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_competition_overs_limit_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_competition_overs_limit_id').parent('.form-group').addClass('has-success');
          }          
          var tw = $('#match_team_won_toss option:selected').text();
          if (tw == "select") {
            $('#match_team_won_toss').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_team_won_toss').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_won_toss').parent('.form-group').addClass('has-success');
          }
          var tc = $('#match_team_choose_to option:selected').text();
          if (tc == "select") {
            $('#match_team_choose_to').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_team_choose_to').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_team_choose_to').parent('.form-group').addClass('has-success');
          } 
          var v = $('#match_venue_id option:selected').text();
          if (v == "select") {
            $('#match_venue_id').parent('.form-group').addClass('has-feedback has-error');
          }
          else {
            $('#match_venue_id').parent('.form-group').removeClass('has-feedback has-error');
            $('#match_venue_id').parent('.form-group').addClass('has-success');
          } 

          var ump = $( 'input[name="match[umpire_ids][]"]:checked' ).length;
          if (ump == 0) {
            $('#umpire_label').parent('.form-group').addClass('has-feedback has-error');
          }
          else if (ump == 1) {
            Command: toastr.error("Umpires selections has be two!");
            $('#umpire_label').parent('.form-group').addClass('has-feedback has-error');
          }

          else {
            $('#new_match').bootstrapValidator('revalidateField', 'match[start_date]'); 
            $('#umpire_label').parent('.form-group').removeClass('has-feedback has-error');
            $('#umpire_label').parent('.form-group').addClass('has-success');
          }
        }

           
        $('#new_match')
            .bootstrapValidator()
              .on('success.form.bv', function(e) {
                  // Called when the form is valid
                  var $form = $(e.target);
                  if ($form.data('remote')) {
                      e.preventDefault();
                      return false;
                  }
              })
              .on('submit', function(e) {
                  var $form = $(e.target);
                  if ($form.data('remote')) {
                      var numInvalidFields = $form.data('bootstrapValidator').getInvalidFields().length;
                      if (numInvalidFields) {
                          e.preventDefault();
                          return false;
                      }
                  }
              });
      });

      (function($) {

        $.fn.modal_success = function(){
          // close modal
          this.modal('hide');

          // clear form input elements
          // todo/note: handle textarea, select, etc
          this.find('form input[type="text"]').val('');

          // clear error state
          this.clear_previous_errors();

          // reload page 
          location.reload();
        };

        $.fn.render_form_errors = function(errors){

          $form = this;
          this.clear_previous_errors();
          model = this.data('model');

          // show error messages in input form-group help-block
          $.each(errors, function(field, messages){
            $input = $('input[name="' + model + '[' + field + ']"]');
            $input.closest('.form-group').addClass('has-error').find('.help-block').html( messages.join(' & ') );
          });

        };

        $.fn.clear_previous_errors = function(){
          $('.form-group.has-error', this).each(function(){
            $('.help-block', $(this)).html('');
            $(this).removeClass('has-error');
          });
        }

      }(jQuery));  

app/views/series/_sidenavbar.html.haml
/ sidebar: style can be found in sidebar.less
%section.sidebar
  / sidebar menu: : style can be found in sidebar.less
  %ul.sidebar-menu
    %li
      %a{href: root_path}
        %i.fa.fa-home
        %span Home
    %li
      %a{href: clubs_path}
        %i.fa.fa-star
        %span Clubs
    %li
      %a{href: teams_path}
        %i.fa.fa-flag
        %span Teams
    %li.active
      %a{href: series_index_path}
        %i.fa.fa-trophy
        %span Series
    %li
      %a{href: matches_path}
        %i.fa.fa-maxcdn
        %span Matches
    %li
      %a{href: players_path}
        %i.fa.fa-group
        %span Players
    %li
      %a{href: umpires_path}
        %i.ion.ion-android-contacts
        %span Umpires
    %li
      %a{href: venues_path}
        %i.fa.fa-umbrella
        %span Venues
    %li.social
      %span
        #{social_share_button_tag("MyClubCricketStats", :url => request.original_url, :image => "http://www.elphax.com/assets/images/my-club-cricket-stats.png", desc: "MyClubCricketStats is a club cricket statics management application where users can create/manage the Clubs, Teams, and Players. MyClubCricketStats will calculate and populates each player and team stats after entering and saving the data.")}        
/ /.sideba

app/views/series/edit.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Home
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home
            Home    
        %li.active
          %a{:href => series_index_path}
            %i.fa.fa-trophy
            Series
    / /.content-header
    %section.content
      .box.box-default
        .box-header
          %h3.box-title Edit Series      
        .box-body  
          = render 'form'
        .box-footer
          %p
            = link_to '<i class="fa fa-fw fa-arrow-circle-left"></i>'.html_safe, series_index_path, :class => "btn btn-default", :title => "Back to series"
            = link_to '<i class="fa fa-fw fa-eye"></i>'.html_safe, @series, :class => "btn bg-maroon", :title => "View series"            
      %br  

app/views/series/index.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Manage Series
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home   
        %li.active
          %a{:href => series_index_path}
            %i.fa.fa-trophy
            Series
    / /.content-header
    %section.content
      .box.box-default
        .box-header
          .pull-right.box-tools
            - if current_user
              = link_to 'New Series', '#new_series_modal', 'data-toggle' => 'modal', :class => 'btn btn-success btn-flat pull-right'
            - else 
              = link_to 'New Series', new_user_session_path, :class => 'btn btn-success btn-flat pull-right'  
            #new_series_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
              .modal-dialog
                .modal-content
                  .modal-header
                    %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
                    %h4#myModalLabel.modal-title Create new club
                  .modal-body
                    = render 'form', modal: true
                  .modal-footer
                    %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
          %h3.box-title Series      
        .box-body  
          .table-responsive 
            %table.table.table-bordered.table-condensed{id: 'series'}
              %thead.series_head
                %tr
                  %th Name
                  %th Start date
                  %th End date
                  %th
              %tbody    
                - @series_all.each do |series|
                  %tr
                    %td= link_to "#{series.name}", series, :title => "View series" 
                    %td= series.start_date
                    %td= series.end_date
                    %td.center
                      - if current_user.present? && series.user_id == current_user.id
                        = link_to '<i class="fa fa-trash-o"></i>'.html_safe, series, method: :delete, data: { confirm: 'This series may have one or more match assigned and by deleting this series will also delete all the matches which are assigned to this series. Are you sure you want to delete?' }, :class => 'btn btn-xs btn-flat btn-danger', :title => "Remove series" 
      %br  

app/views/series/new.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Manage Series
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home   
        %li.active
          %a{:href => series_index_path}
            %i.fa.fa-trophy
            Series
    / /.content-header
    %section.content
      .box.box-default
        .box-header
          %h3.box-title New Series      
        .box-body  
          = render 'form'
        .box-footer
          %p
            = link_to '<i class="fa fa-fw fa-arrow-circle-left"></i>'.html_safe, series_index_path, :class => "btn btn-default", :title => "Back to series"           
      %br  

app/views/series/new_series.js.haml
$('#new_series_modal').modal_success();

app/views/series/show.html.haml
.wrapper.row-offcanvas.row-offcanvas-left
  / Left side column. contains the logo and sidebar
  %aside.left-side.sidebar-offcanvas
    = render 'sidenavbar'
  / Right side column. Contains the navbar and content of the page
  %aside.right-side
    %header.row
      %section.jumbotron.top-header
        %figure
          = image_tag 'logo.png', :alt => "logo", :class => "header_image_responsive" 
    %section.content-header     
      %h1 Manage Series
      %ol.breadcrumb
        %li
          %a{:href => root_path}
            %i.fa.fa-home    
        %li.active
          %a{:href => series_index_path}
            %i.fa.fa-trophy
            Series
    / /.content-header
    %section.content
      .box.box-default
        .box-header
          %h3.box-title Series Details      
        .box-body  
          .table-responsive 
            %table.table.table-bordered.table-striped
              %thead.umpire_head
                %tr
                  %th Name
                  %td= @series.name
                %tr
                  %th Start Date
                  %td= @series.start_date
                %tr
                  %th End Date
                  %td= @series.end_date
          %br
      
      .box.box-info
        .box-header
          .pull-right.box-tools
            - if current_user
              = link_to 'New Match', '#new_match_modal', 'data-toggle' => 'modal', :class => 'btn btn-success btn-flat pull-right'
              #new_match_modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
                .modal-dialog
                  .modal-content
                    .modal-header
                      %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} &times;
                      %h4#myModalLabel.modal-title Create New Match
                    .modal-body
                      = render 'match_form', modal: true, series: @series.id
                    .modal-footer
                      %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close 
            - else 
              = link_to 'New Match', new_user_session_path, :class => 'btn btn-success btn-flat pull-right'
       
          %h3.box-title Series Matches     
        .box-body  
          - @series.matches.each_with_index do |m, index|
            .row.match-event-box          
              .col-lg-1.match-type-box 
                %h6 
                  %span.badge.bg-teal #{index+1}
                  %hr
                  %b #{m.competition_type.name}                
              .col-lg-7.matchCompetitors 
                %h4 #{link_to "#{m.team_a.name}", team_path(m.team_a.id), :title => "View team" }
                .teamLogos #{image_tag "teams/#{m.team_a.team_flag.file_name}", :class => 'flag_big_icon img-thumbnail-circle'}
                %h5 vs
                .teamLogos #{image_tag "teams/#{m.team_b.team_flag.file_name}", :class => 'flag_big_icon img-thumbnail-circle'}                
                %h4 #{link_to "#{m.team_b.name}", team_path(m.team_b.id), :title => "View team" }
              .col-lg-4.matchDetails
                %h5 #{m.team_won_toss} won the toss and decided to #{m.team_choose_to}!             
                %h5 Please complete scorecard entries for match result.
                %span= link_to '<i class="fa fa-list fa-fw"></i> Scorecard'.html_safe, match_path(m), :class => "btn btn-default", :title => "Back to series"
                %span= link_to '<i class="fa fa-trash-o"></i>'.html_safe, match_path(m, "show"=>"series_show"), :method => :delete, :data => { :confirm => 'By deleting this match will also delete all of the match details including scorecard and players stats. Are you sure you want to delete?' }, :class => 'btn btn-danger', :title => "Remove match"
                %br
      %br 
      = link_to '<i class="fa fa-fw fa-arrow-circle-left"></i>'.html_safe, series_index_path, :class => "btn btn-default", :title => "Back to series"
      %br
      %br
      %br      